version: '3'
services:
  db:
    image: "wnameless/oracle-xe-11g-r2"
    environment:
      - ORACLE_DISABLE_ASYNCH_IO=true
      - ORACLE_ALLOW_REMOTE=true
      - WEB_CONSOLE=false
    ports:
      - "1521:1521"
    volumes:
      - ./oracle/small-fast.sql:/docker-entrypoint-initdb.d/small-fast.sql