package com.sokkun.smallfasttransfer.repository

import com.sokkun.smallfasttransfer.domain.model.ParticipantUser
import org.springframework.data.jpa.repository.JpaSpecificationExecutor
import org.springframework.data.repository.PagingAndSortingRepository

interface ParticipantUserRepository: PagingAndSortingRepository<ParticipantUser, Long>, JpaSpecificationExecutor<ParticipantUser>